import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeLayout from '../Layout/HomeLayout.js'
import UserSeclect from '../Utils/SelectUser'
import { Card } from 'antd'
import Products from '../Utils/Products'
import ProductModal from '../Utils/ProductModal'
import { Row, Col, Divider } from 'antd';
import { SetStateAction, useState } from 'react'

export default function Home({ initialPosts }) {
  const [productState, setProductState] = useState(initialPosts);
  const [userIdState, setUserIdState] = useState("select");
  const [commissionValue, setCommissionValue] = useState({point: "", point_in_tk:"", user_type: ""})

  const getAllData = async () => {
    const url = `http://localhost:3000/api/product/all`;
    const headers = {
      'Content-Type': 'application/json'
    };
    const response = await fetch(url, { method: 'GET', headers });
    const resData = await response.json();
    console.log("resData", resData)

    setProductState(
      resData.data
    )
  }

  const childHandler = async (value) => {
    setUserIdState(value)
    if (value == "select"){
      setCommissionValue(
          commissionValue = {point: "", point_in_tk:"", user_type: ""}
      )
    }else{
      console.log("value", value)

      const res = await fetch(`http://localhost:3000/api/commission/${value}`)
      const allUser = await res.json()
      console.log("allUser", allUser)
      setCommissionValue(
          commissionValue = allUser.data
      )
    }
  }

  const childHandler2 = async (value) => {
    await childHandler(value)
  }

  return (
    <HomeLayout>
    <div>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card style={{ minHeight: '100vh' }}>
        <UserSeclect action={childHandler} commissionValue={commissionValue} />
        

        <Row gutter={16}>
          <Col className="gutter-row" span={24}>
            <div>
              <Products action={childHandler2} allItems={productState} userId={userIdState}/>
            </div>
          </Col>
        </Row>

      
      

      <ProductModal getAllData={getAllData} />

      </Card>

      
    </div>
    </HomeLayout>
  )
}

export const getServerSideProps = async (context) => {
  const res = await fetch(`http://localhost:3000/api/product/all`)
  const oneItem = await res.json()
  console.log("oneItems", oneItem)
  return {
    props: {
      initialPosts: oneItem.data
    },
  }
}